### ISSUE TITLE
Make violin plots of candidate TREGs and POLR2A

### ISSUE THREAD

**Issue by lahuuki** [LieberInstitute/TREG_paper#2]
Check out distribution of expression of the four genes in Matt's data and Mathy's data across cell type. Check GTEx expression browser for expression across tissues.
 
"show that a TREG doesn't have constant expression across cell types whereas a housekeeping gene is supposed to have constant expression across tissues"

**Comment by lcolladotor** [comment]
https://gtexportal.org/home/gene/POLR2A looks more stable (although still variable) across tissues than https://gtexportal.org/home/gene/AKT3
